# Generated by Django 4.2.1 on 2023-05-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
