# Generated by Django 4.2.1 on 2023-05-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='UTC', max_length=30),
        ),
        migrations.CreateModel(
            name='Mitienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(default='UTC', max_length=30)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('nroCelular', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('propietario', models.CharField(max_length=50)),
                ('horaios', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.usuario')),
            ],
        ),
    ]
