# Generated by Django 4.2.1 on 2023-05-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0003_usuario_pais_mitienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitienda',
            old_name='Pais',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='mitienda',
            name='web',
            field=models.URLField(default='https://match-music.netlify.app/'),
        ),
    ]
