# Generated by Django 4.2.1 on 2023-05-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0004_rename_pais_mitienda_pais_mitienda_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('precioXu', models.FloatField(max_length=10)),
                ('precioXm', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TdaPto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_t1', models.ManyToManyField(to='BaseCentral.mitienda')),
            ],
        ),
    ]
