# Generated by Django 4.2.1 on 2023-05-21 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0005_producto_tdapto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.time)),
                ('pais', models.CharField(default='UTC', max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('cp', models.IntegerField()),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime)),
                ('cantidadDeVentas', models.IntegerField(default=0)),
                ('vendedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tdapto',
            name='id_p1',
            field=models.ManyToManyField(to='BaseCentral.producto'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date)),
                ('aNombrede', models.CharField(max_length=50)),
                ('nroPedido', models.IntegerField()),
                ('tipoDeEnvio', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=100)),
                ('id_t2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.mitienda')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.timedelta)),
                ('cuit', models.IntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('preciosXu', models.FloatField(max_length=10)),
                ('preciosXm', models.FloatField(max_length=10)),
                ('valorTotal', models.FloatField(max_length=12)),
                ('id_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.venta')),
            ],
        ),
        migrations.CreateModel(
            name='FacEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_e1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.envio')),
                ('id_f1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.factura')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='id_f2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.factura'),
        ),
    ]
