# Generated by Django 4.2.1 on 2023-06-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0005_remove_mitienda_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitienda',
            name='usuario',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
