# Generated by Django 4.2.1 on 2023-06-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0006_mitienda_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitienda',
            old_name='usuario',
            new_name='usuario',
        ),
    ]
