# Generated by Django 4.2.1 on 2023-06-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0007_rename_usuario_mitienda_usuarioo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitienda',
            name='usuario',
        ),
    ]
