# Generated by Django 4.2.1 on 2023-05-31 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0007_category_remove_pedido_id_t2_remove_tdapto_id_t1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseCentral.category'),
        ),
    ]
