# Generated by Django 4.2.1 on 2023-05-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0008_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.TextField(default='', max_length=250),
        ),
    ]
