# Generated by Django 4.2.1 on 2023-06-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('BaseCentral', '0009_mitienda_usuario_producto_tiendade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users',
        ),
    ]
