# Generated by Django 4.2.1 on 2023-06-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseCentral', '0010_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
    ]
